### ISSUE TITLE
Ideal README.md

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#11]
# Carrot™
>A Simple Node.js Neural Network Library

[![Carrot's Build Status](https://img.shields.io/badge/Build-passing-brightgreen.svg)](https://github.com/liquidcarrot/carrot/issues) [![Carrot's Code Coverage](https://img.shields.io/badge/Code%20Coverage-0.0%25-red.svg)](https://github.com/liquidcarrot/carrot/issues) [![Carrot's Current Version](https://img.shields.io/badge/Version-0.1.4-brightgreen.svg)](https://github.com/liquidcarrot/carrot/issues) [![Carrot's Weekly Download](https://img.shields.io/npm/dw/@liquid-carrot/carrot.svg)](https://www.npmjs.com/package/@liquid-carrot/carrot) [![Carrot's License](https://img.shields.io/badge/License-MIT-blue.svg)](/LICENSE) [![Carrot's Love](https://img.shields.io/badge/Made%20with%20%E2%99%A5%20by-Liquid%20Carrot-ff1414.svg)](https://github.com/liquidcarrot/carrot/issues)

## Table of Contents

<details>
  <summary><strong>Table of Contents</strong></summary>

  * [Installation]()
  * [Getting Started]()
  * [Examples]()
  * [Resources]()
  * [Contributing]()
  * [Credits]()
  * [Contributors]()
  * [Road Map]()
  * [License]()
</details>

## Installation

```bash
$ npm i -S liquid-carrot
```

## Getting Started

```javascript
let carrot = require('@liquid-carrot/carrot')

let net = new carrot.Network()
```

## Examples 

* [Example 1](https://liquidcarrot.io)
* [Example 2](https://liquidcarrot.io)

## Resources

* [Resource 1](https://liquidcarrot.io)
* [Resource 2](https://liquidcarrot.io)

## Contributing
Carrot™ is a open source  project. We invite your participation through issues
and pull requests!

When adding or changing a service please add tests.

If you're new to the project, maybe you'd like to open a pull request to address one of them:

[![Carrot's GitHub Issues](https://img.shields.io/github/issues/liquidcarrot/carrot.svg)](https://github.com/liquidcarrot/carrot/issues)

## Credits

* [**`gpu.js`**](https://www.npmjs.com/package/gpu.js)
* [**`neo-async`**](https://www.npmjs.com/package/neo-async)
* [**`bluebird`**](https://www.npmjs.com/package/bluebird)
* [**`lodash`**](https://www.npmjs.com/package/lodash)
* [**`thaw.js`**](https://www.npmjs.com/package/thaw.js)

## Contributors 
[![Carrot's Code Contributors](https://img.shields.io/badge/Contributors-2-yellow.svg)](https://github.com/liquidcarrot/carrot/issues)

This project exists thanks to all the people who contribute. We can't do it without you! 🙇

* [Luis Carbonell](https://twitter.com/luis_carbnell)
* [Christian Echevarria](https://twitter.com/chrisgereina)

## Backers
[![Carrot's Financial Backers](https://img.shields.io/badge/Backers-5-brightgreen.svg)](https://github.com/liquidcarrot/carrot/issues)

Thank you to all our backers! 🙏 [[Become a backer](https://liquidcarrot.io/)]

![Become a Backer](https://i.imgur.com/KjS41CZ.png)

## Sponsors
[![Carrot's Sponsors](https://img.shields.io/badge/Sponsors-1-brightgreen.svg)](https://github.com/liquidcarrot/carrot/issues)

Support this project by becoming a sponsor. Your logo will show up here with a link to your website. [[Become a sponsor]()]

![Become a Sponsor](https://i.imgur.com/xTv3pnw.png)

## Patrons
[![Carrot's Patrons](https://img.shields.io/badge/Patrons-0-yellow.svg)](https://github.com/liquidcarrot/carrot/issues)

Thank you to all of our patrons! 🙏 [[Become a Patron](https://www.patreon.com/liquidcarrot)]

[![Become a Patron](https://c5.patreon.com/external/logo/become_a_patron_button.png)](https://www.patreon.com/liquidcarrot)

## Documentation
* [Getting Started]()
* [Reference]()

## Used By

* [Company 1]()
* [Company 2]()
* [Company 3]()
* [Project 1]()
* [Project 2]()
* [Organization 1]()

## Feedback
Feel free to send us feedback on [Twitter]() or [file an issue](). Feature requests are always welcome. If you wish to contribute, please take a quick look at the [guidelines]()!

If there's anything you'd like to chat about, please feel free to join our [Discord chat]()!

## Road Map
More coming soon...

## License
Carrot™ is available under the [MIT License](LICENSE)

**Comment by luiscarbonell** [comment]
## Examples
* https://github.com/Patreon/PTRManualLayout/blob/master/README.md
* https://github.com/RichardLitt/standard-readme
* https://github.com/ai/size-limit
* https://github.com/aimeos/aimeos-typo3
* https://github.com/amitmerchant1990/electron-markdownify
* https://github.com/anfederico/Clairvoyant
* https://github.com/angular-medellin/meetup
* https://github.com/athityakumar/colorls
* https://github.com/choojs/choo
* https://github.com/gitpoint/git-point
* https://github.com/nhnent/tui.editor
* https://github.com/Hexworks/zircon
* https://github.com/php-censor/php-censor
* https://github.com/webpro/release-it
* https://github.com/sourcerer-io/sourcerer-app#contributing
* https://github.com/shama/gaze
* https://github.com/sebyddd/SDVersion

**Comment by luiscarbonell** [comment]
# Carrot™
>A Simple Node.js Neural Network Library

[![Carrot's Weekly Download](https://img.shields.io/npm/dw/@liquid-carrot/carrot.svg)](https://www.npmjs.com/package/@liquid-carrot/carrot) [![Carrot's License](https://img.shields.io/badge/License-MIT-blue.svg)](/LICENSE) [![Carrot's Love](https://img.shields.io/badge/Made%20with%20%E2%99%A5%20by-Liquid%20Carrot-ff1414.svg)](https://github.com/liquidcarrot/carrot/issues)

## Contributing
[![Carrot's GitHub Issues](https://img.shields.io/github/issues/liquidcarrot/carrot.svg)](https://github.com/liquidcarrot/carrot/issues)

Carrot™ is a open source  project. We invite your participation through issues
and pull requests!

When adding or changing a service please add tests.

If you're new to the project, maybe you'd like to open a pull request to address one of them. 😜

## Contributors
This project exists thanks to all the people who contribute. We can't do it without you! 🙇

* [Luis Carbonell](https://twitter.com/luis_carbnell)
* [Christian Echevarria](https://twitter.com/chrisgereina)

**Comment by luiscarbonell** [comment]
**Great Tagline:** 
>"High Performance, High Flexibility, Node.js Async & Streaming, Neural Network Library"

**Comment by luiscarbonell** [comment]
Will keep as reference. But will close for now.

Deciding on an ideal `README.md` won't be a priority again, for a while.

**Comment by luiscarbonell** [comment]
Going to re-open for https://github.com/liquidcarrot/carrot/projects/5

**Comment by christianechevarria** [comment]
This project is now closed: https://github.com/liquidcarrot/carrot/projects/5

Closing for now.
