### ISSUE TITLE
neat.evolve() crashes when fitness set to null 

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#115]
Running my code I now have this error
`ReferenceError: Parameter "dataset" is required; parameter "dataset" is missing. `

Code:
` neat.evolve(null, filter, adjust);`

It seems that evolve no longer allows null datasets.

**Comment by luiscarbonell** [comment]
I'm looking into now @dan-ryan

**Comment by dan-ryan** [comment]
This looks like the build that broke it.
https://github.com/liquidcarrot/carrot/commit/31f8e87cc0ded1a3f1eb3a450ccafa4d426153f1

And this one expanded on it:
https://github.com/liquidcarrot/carrot/commit/639213b08759ec830752456c2b926c2f85e9644a

**Comment by luiscarbonell** [comment]
I'm skimming through it now.

**Comment by luiscarbonell** [comment]
Will have to write test for these use cases 👌

**Comment by luiscarbonell** [comment]
I'll send a quick patch and leave this issue open - till tests are created.

**Comment by luiscarbonell** [comment]
@dan-ryan Just created a [PR](https://github.com/liquidcarrot/carrot/pull/116) - I basically reverted some of the changes, temporarily. 

We've been cleaning, to start writing cleaner tests. Hoping to have these testing/clean code issues resolved in <3 weeks.

**Comment by dan-ryan** [comment]
I cherry-picked those fixes but it now expects fitness to not be null.

**Comment by luiscarbonell** [comment]
@dan-ryan Looks like it's going to take me a little longer than expected - going to grab a bite and try to roll through it. 

There's some duplicate code in `Neat` and in `Network` (with NEAT). 

I'm going to clean them up a bit, so I can phish out these things.

**Comment by dan-ryan** [comment]
Yeah no rush :)

**Comment by luiscarbonell** [comment]
@dan-ryan We finished the cleaning portion yesterday (https://github.com/liquidcarrot/carrot/projects/11);  I think we found a few things. We're taking a couple hours today to plan how to fix them all, we'll put this _(and other `.evolve()` related things)_ on top on the priority list

**Comment by dan-ryan** [comment]
My main project has to use the old version because this still doesn't work.

**Comment by nicszerman** [comment]
@dan-ryan based on what would a network be evolved if there is no dataset
supplied? Using only the fitness function?

*Nicholas Szerman*

**Comment by dan-ryan** [comment]
@nicolares20 
"based on what would a network be evolved if there is no dataset supplied"
Games. This was created in Neataptic: https://github.com/zonetti/snake-neural-network/

In my example, I do have a dataset, but I can't do what I need. No way to get Carrot to create my custom bot class which I use to store all the data about the bot so I can calculate its score.

**Comment by luiscarbonell** [comment]
We should have a way to solve this in the coming patch - but using network, not yet `NEAT`.

Starting to work on the "new architecture" to start supportin HyperNEAT/otNEAT/etc. - this should be very do-able after that's knocked out. If you want to collab on the design, let me know we're using a Miro board right now.

**Comment by christianechevarria** [comment]
Hey @dan-ryan! Just added some changes in 81f126c1e7e84cd131d8c2e25c2f31fbe13665eb and added some tests for the different use-cases

**Comment by christianechevarria** [comment]
The changes should support these use-cases now:

- new Neat(dataset) | Neat.evolve(otherSet), prioritizes `otherSet`
- new Neat(dataset) | Neat.evolve(), falls back to `dataset`
- new Neat() | Neat.evolve(otherSet), uses `otherSet` 
- new Neat() | Neat.evolve(), uses `.score` property to evolve

**Comment by christianechevarria** [comment]
One more thing to note is we decided to update `Neat.evolve` to return a sorted population instead of just the fittest network in case there are use-cases where the entire population is useful. Since the population is sorted you can always expect `Neat.population[0]` to be the fittest genome

**Comment by christianechevarria** [comment]
@dan-ryan Let me know if the changes work for you

Closing this for now

**Comment by dan-ryan** [comment]
No this does not work for me.

Getting a crash `self.fitness is not a function`. On this line:
`genome.score = await self.fitness(dataset, genome);`

Line 679 in neat.js.

**Comment by dan-ryan** [comment]
Still doesn't work for me.

If you set `fitness` to null, it crashes.

If you don't set `fitness`, it will never increase the generation number. It seems to never return from:
`genome.score = await self.fitness(dataset, genome);`. It might be because it's getting a score of NaN.

**Comment by dan-ryan** [comment]
I added a null check for `fitness`. It's now working poorly. 
Again it will never increase the generation number. It never returns from this method:
`await self.evaluate(evolve_dataset);`

**Comment by dan-ryan** [comment]
Nice, glad you found the problem.

**Comment by dan-ryan** [comment]
Can you update the version? I'll test it out once you do.

**Comment by christianechevarria** [comment]
Just updated 🎊

**Comment by dan-ryan** [comment]
No longer handles null scores. But once I fixed that it seems to be increasing generations now. 

I'm having trouble getting it to learn the dataset. But maybe I need to tweak the script for the latest changes.

**Comment by christianechevarria** [comment]
> No longer handles null scores (sounds like an issue?). But once I changed that in my code it seems to be increasing generations now.

On the fence about it, but added the thrown `null` in https://github.com/liquidcarrot/carrot/blob/master/src/neat.js#L403 to catch any situations where scores become null during program execution, saw it pay off while collaborating on a demo with @AkashSamlal but I imagine there could be some cases where null scores are desirable / useful 

Thinking about switching this to a warning that will display if logging options are enabled -- what do you think?

**Comment by christianechevarria** [comment]
Neat.evolve seems to be working without fitness functions or datasets, this demo is a sort of end-to-end test for it: https://liquidcarrot.io/example.flappy-bird/

Closing for now
