### ISSUE TITLE
evolve crashes (looks like cut-and-paste errors)

### ISSUE THREAD

**Issue by tracycollins** [liquidcarrot/carrot#120]
### Description
It looks like some cut-and-paste errors in the serialize function:

 -- Variable: 'incoming_connectionections_index' should be 'incoming_connections_index'
 -- Variable 'connectionections' should be 'connections'

`  serialize: function serialize() {
   ...

      _.times(node.connections.in.length, (incoming_connections_index) => {
        const connection = node.connectionections.in[incoming_connectionections_index];

        connectionections.push(connection.from.index);
        connectionections.push(connection.weight);
        connectionections.push(connection.gater == null ? -1 : connection.gater.index);
      });

      connections.push(-2); // stop token -> next node
    }

    return [activations, states, connections];
  }
`

AND

In the 'evolve' function, the array 'workers' is declared such that it's undefined in this block:

`    if (options.threads > 1) {
      for (let i = 0; i < workers.length; i++) workers[i].terminate();
    }
`
### Files
src/architecture/network.js

### To Reproduce
Run XOR example and it crashes

**Comment by christianechevarria** [comment]
Awesome catch @tracycollins! We'll get on this ASAP

Looping in:
@nicszerman @luiscarbonell

**Comment by nicszerman** [comment]
I'll get on it today! Great job with the report!!

**Comment by nicszerman** [comment]
Fixed.
