### ISSUE TITLE
Change node.noTraceActivate() to make it an option of the regular node.activate()

### ISSUE THREAD

**Issue by nicszerman** [liquidcarrot/carrot#133]
Also change network.activate(), which internally calls noTraceActivate().

The proposed solution would be to use `node.activate({no_trace: true/false})`

**Comment by christianechevarria** [comment]
Resolved by 74d495394d246fb25a80543411bca75d9c6e8a0a e7eb40acfbf3eb1cf320c5ed37520dfeddd20fef
