### ISSUE TITLE
Stop using Network.fromJSON(network.toJSON()) to clone networks.

### ISSUE THREAD

**Issue by nicszerman** [liquidcarrot/carrot#137]
Not only it is super slow, there's also no point.
Proposed solutions:
1. `new Network(network)`
2. `network.clone()` -- why use this when we can do (1.) ?

**Comment by dan-ryan** [comment]
https://github.com/liquidcarrot/carrot/issues/84

**Comment by nicszerman** [comment]
Closed since #84 fixes this
