### ISSUE TITLE
Sample LSTM & GRU code crashes

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#140]
`let LSTM = new architect.LSTM(4, 5, 1);`
Crashes with "You have to specify at least 3 layer_sizes".

Problem code:

```
    const layer_sizes_and_options = Array.from(arguments);

    const output_size_or_options = layer_sizes_and_options.slice(-1);
    
    let layer_sizes, options
    
    // find out if options were passed
    if (typeof output_size_or_options === 'number') {
      layer_sizes = layer_sizes_and_options;
      options = {};
    } else {
      layer_sizes = layer_sizes_and_options.slice(layer_sizes_and_options.length - 1);
      options = output_size_or_options;
    }

    if (layer_sizes.length < 3) {
      throw new Error('You have to specify at least 3 layer_sizes');
    }
```
`layer_sizes.length` returns 1.

**Comment by nicszerman** [comment]
I just fixed this issue yesterday night in the branch testing. We're about
to do a big merge with master, pushing a ton of bug fixes, many tests, and
some breaking changes.

*Nicholas Szerman*

**Comment by dan-ryan** [comment]
`let GRU = new architect.GRU(4, 5, 1);` also crashes with "ReferenceError: blocks is not defined".

**Comment by luiscarbonell** [comment]
Keeping it open until we merge into master.

**Comment by nicszerman** [comment]
@dan-ryan that was also fixed

**Comment by luiscarbonell** [comment]
Going to close thanks to `v0.3.0` .
