### ISSUE TITLE
how does speciation works ?

### ISSUE THREAD

**Issue by winatawelly** [liquidcarrot/carrot#145]
i cant find any mention about species/speciation on the docs page, am i missing  something or it hasnt been implemented yet ?

**Comment by luiscarbonell** [comment]
@winatawelly It's in the works. There is some partial speciation that's happening behind the scenes but it  hasn't been exposed through the API yet.

**Comment by winatawelly** [comment]
> @winatawelly It's in the works. There is some partial speciation that's happening behind the scenes but it hasn't been exposed through the API yet.

good to know, thanks!
