### ISSUE TITLE
question about neat.evolve()

### ISSUE THREAD

**Issue by winatawelly** [liquidcarrot/carrot#147]
on the documentation page about neat.evolve [here](https://liquidcarrot.io/carrot/Neat.html), there are "pick" and "adjust". but at the very bottom of code snippet, evolve is using "filter" which is never defined.

    let pick = function pickGenome(genome) return genome.nodes.length > 100 ? true : false // Remove genomes with more than 100 nodes
    let adjust = function adjustGenome(genome) return genome.clear() // clear the nodes

    neat.evolve(null, filter, adjust)

and when i tried replacing "filter" with "pick", the code returned an error

    ReferenceError: adjustGenome is not defined
    at Neat.self.evolve (/home/winatawelly/Code/carrot/node_modules/@liquid-carrot/carrot/src/neat.js:494:87)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
    (node:15610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:15610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

can someone explain this ?

**Comment by luiscarbonell** [comment]
Will look at a fix...looks like that slipped through during our last big push for a test suite.

**Comment by christianechevarria** [comment]
Hi @winatawelly I'll be cleaning up this code, should have a fix and explanation for you very soon!

**Comment by christianechevarria** [comment]
Hi @winatawelly! Okay so, `Neat.evolve` gives the user the ability to manually pick and filter networks as they get mutated at a couple points (before and after mutation) and it uses a function called `Neat.replace` to do that. It seems like there was a disconnect between the code inside `Neat.evolve` and the new `Neat.evolve` so that was just updated. 

Here are the docs entries, everything should be running smoothly but we have yet to run proper tests on this 

See the new docs entry here:

https://liquidcarrot.io/carrot/Neat.html#.replace

https://liquidcarrot.io/carrot/Neat.html#evolve

Closing this one for now 👍

**Comment by winatawelly** [comment]
> Hi @winatawelly! Okay so, `Neat.evolve` gives the user the ability to manually pick and filter networks as they get mutated at a couple points (before and after mutation) and it uses a function called `Neat.replace` to do that. It seems like there was a disconnect between the code inside `Neat.evolve` and the new `Neat.replace` so that was just updated.
> 
> The docs were based on an older version of the function so there was a mismatch -- just updated and everything should be running smoothly
> 
> See the new docs entry here:
> 
> https://liquidcarrot.io/carrot/Neat.html#.replace
> 
> https://liquidcarrot.io/carrot/Neat.html#evolve
> 
> Closing this one for now 👍

appreciate it, thanks mate!
