### ISSUE TITLE
Synaptic.js -> Neataptic

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#19]
[Synaptic.js](https://github.com/cazala/synaptic) is not built as well and does not support as many features as [Neataptic](https://github.com/wagenaartje/neataptic) right out of the gate. 

I think we should make the change from one to the other - and am going to go ahead and get started with it.

**Comment by christianechevarria** [comment]
Sounds great!

**Comment by luiscarbonell** [comment]
We got the code migrated. Going to close for now.
