### ISSUE TITLE
gitFittest & gitAverage are sync functions calling async ones.

### ISSUE THREAD

**Issue by missionz3r0** [liquidcarrot/carrot#211]
As a precursor, I'm willing to make these changes myself. But want to make sure there is not a reason for these functions to be the way they are before doing so.

### Description
In neat:

getFittest and getAverage both call the async method evaluate while being sync methods. This causes unexpected behavior when calling getFittest or getAverage. The function only checks the first two items in the population against eachother, which only guarantees those two items are sorted against eachother. Seems this was an issue back in neataptic too. 

See wagenaartje/neataptic#137
and wagenaartje/neataptic#100

### Files
You can see the function I am talking about [here](https://github.com/liquidcarrot/carrot/blob/13bcce374174b39a5e6d73dcb5d976631f43e7ff/src/neat.js#L663). 

### To Reproduce
Just call getFittest, or getAverage.

### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- Make getFittest async, and have it await the evaluate function
- Make getAverage async, and have it await the evaluate function

**Comment by christianechevarria** [comment]
@missionz3r0 thanks for writing such a well articulated issue; this was an issue that we noted but seemed to slip through the cracks as we were working on the codebase. I'll merge your PR now 👍

**Comment by missionz3r0** [comment]
@christianechevarria Thank you very much.

It was something I noticed in neataptic a couple days ago before I realized Carrot was a thing. Was surprised when the same issue was over here as well. Though, if not for the issue in neataptic I would not have known carrot was a thing. So all is well that ends well.

**Comment by christianechevarria** [comment]
@missionz3r0 Welcome to the community then! 😄 We have a few projects going on, as of late we are working to refactor the library and migrate to TS to make it more maintainable in preparation to add more features + new algo implementations
