### ISSUE TITLE
Privatize internal objects in documentation

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#22]
Add **@private** tag to the following things in the documentation:

- [Class.TestWorker](https://liquidcarrot.io/carrot/TestWorker.html)
- [Module.Carrot](https://liquidcarrot.io/carrot/module-Carrot.html)
- [Global.config](https://liquidcarrot.io/carrot/global.html#config)

**Comment by christianechevarria** [comment]
Resolved by `a436859`
