### ISSUE TITLE
Is this the correct way to implement a hopfield network?

### ISSUE THREAD

**Issue by raimannma** [liquidcarrot/carrot#220]
https://github.com/liquidcarrot/carrot/blob/bf9ae22199c77911f8e6da474e04be943f92296f/src/architecture/architect.js#L466-L498

If this is correct than a hopfield network is just a simple perceptron but with STEP activation function. 

I found this pics of hopfield networks:
![image](https://user-images.githubusercontent.com/26171511/78834061-3e24d500-79ee-11ea-8887-026c414111fd.png)
![image](https://user-images.githubusercontent.com/26171511/78834099-50067800-79ee-11ea-8612-3a42728e68f6.png)
![image](https://user-images.githubusercontent.com/26171511/78834110-585eb300-79ee-11ea-8fd4-3c37679b5a7d.png)

They seem like there is more ongoing then just a dense layer with step activation, or am I wrong?

Also Wikipedia says: "A Hopfield network is a form of recurrent artificial neural network" ([Wikipedia](https://en.wikipedia.org/wiki/Hopfield_network)). But there are only feedforward components.

**Comment by christianechevarria** [comment]
You're absolutely right about it being more complex than just a dense feed-forward network. To my understanding in a hopfield network all nodes connect to all other nodes so implementation-wise this depends on whether the `methods.connection.ALL_TO_ALL` connection method is implemented correctly inside of `Group.connect()`

**Comment by raimannma** [comment]
`ALL_TO_ALL` means 
```
input0 -> output0
input0 -> output1
input1 -> output0
input1 -> output1
```

but there should be backward pointing connections right ?

**Comment by christianechevarria** [comment]
> but there should be backward pointing connections right ?
> 
> Like this?
> 
> ```
> input0 -> output0
> input0 -> output1
> input1 -> output0
> input1 -> output1
> output0 -->input0
> output0 -->input1
> output1 -->input0
> output1 -->input1
> ```

Yes exactly, we could create a new connection method that does this. Also, `ALL_TO_ALL` is a bit misleading in this context I wonder if we should rename it

**Comment by raimannma** [comment]
Ok, consider renaming it to `ALL_TO_ALL_FORWARD` ?

And we need no additional connection type we can just do:

```
input.connect(output, methods.connection.ALL_TO_ALL);
output.connect(input, methods.connection.ALL_TO_ALL);
```

**Comment by christianechevarria** [comment]
That's true and much more elegant :+1: renaming sounds good also

**Comment by christianechevarria** [comment]
We should also have some basic structural tests for architecture to avoid things like this slipping through
