### ISSUE TITLE
WAPE cost method

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#26]
Neataptic has a pull request for Weighted Absolute Percentage Error (WAPE) that was never merged in (unmaintained). Maybe something we would want to merge in here?

https://github.com/wagenaartje/neataptic/pull/132

**Comment by luiscarbonell** [comment]
@dan-ryan Absolutely! 

I see that you approved the previous one's on Neataptic. If you want to pull request it in, I'll be up for a few more hours to quickly approve the request. 👍 

I can also get it in myself tonight - but I wouldn't want to steal @wilconsonj's or your thunder! 🤷‍♂️

**Comment by luiscarbonell** [comment]
@christianechevarria Have been looking at collecting a list of them (e.g [this](https://stats.stackexchange.com/questions/154879/a-list-of-cost-functions-used-in-neural-networks-alongside-applications) but better documented and more simplified)

In other words, feel free to shoot as many as these as you'd like into the issue's and we'll tackle them as fast as we can!

**Comment by luiscarbonell** [comment]
@dan-ryan I got a little too excited about having our first third-party issue, so I went ahead and added WAPE to our cost functions! 3a1c8f8039d055d0a658d07a78639b11e64fff41

I can credit the commit to you if you shoot over a no-reply GH email to me at luis@liquidcarrot.io

Thank you for taking the time to be a part of the JavaScript AI community!

**Comment by dan-ryan** [comment]
"I got a little too excited about having our first third-party issue, so I went ahead and added WAPE to our cost functions!"
Haha, all good. 

Happy to help :)
