### ISSUE TITLE
EfficientMutation flag for neat

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#27]
Neataptic has a pull request for EfficientMutation flag that was never merged in (unmaintained). 

> "Before it attempts to do any mutations, it checks which mutations are possible on the genome from the selected mutation types, and passes them to be utilized from the selectMutationMethod."

Maybe something we would want to merge in here or look into? I've tested it on my own project and seems to work fine. 

https://github.com/wagenaartje/neataptic/pull/79

**Comment by christianechevarria** [comment]
@dan-ryan Just added in `7435319`

Thanks for opening up the issue 👍
