### ISSUE TITLE
Object parameters and property rendering is broken in documentation

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#32]
**Describe the bug**
Object documentation is broken in broken in Chrome - i.e. not responsive.

![Broken Liquid Carrot Documentation](https://user-images.githubusercontent.com/775672/56706795-68906a80-676a-11e9-85a7-6c2b436910e8.PNG)

**Comment by christianechevarria** [comment]
Fixed with 91fe43a9c9b9bf7a6558baedbead5cada8ce162d
