### ISSUE TITLE
Moved: New nodes should not get random activation if not allowed

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#36]
This bug has been moved from Neataptic.
https://github.com/wagenaartje/neataptic/issues/53

> If a network gets mutated from a `Neat` instance with `mutation.ADD_NODE`, the new node should only get a random activation if `mutation.MOD_ACTIVATION` is present in `Neat.mutation`.
> 
> ```js
> // Random squash function
> node.mutate(mutation.MOD_ACTIVATION);
> ```
> 
> [Line 289](https://github.com/wagenaartje/neataptic/blob/5a26f044ca6411594fcf11aab975279fc4c8f7dd/src/architecture/network.js#L289)

**Comment by christianechevarria** [comment]
Removed in  6f2383b4f7cd6545c014768e5814f4354bd5efe4

Briefly added a check for `mutation.MOD_ACTIVATION` before mutating the new node but it didn't seem worth the performance cost

**Comment by christianechevarria** [comment]
@dan-ryan After some more testing, confirmed that this makes converging on a solution more difficult (which makes sense)

I'm thinking about reintroducing this but adding a flag to overwrite the default behavior.

Any thoughts?

**Comment by dan-ryan** [comment]
"but it didn't seem worth the performance cost"
One check hurt the performance that much?

Otherwise could just make it clear in the docs that there is this side effect.

**Comment by christianechevarria** [comment]
Restored it in f27e594fbaec0783d34035ab68fbbd5b233b1217

Just ended up adding a `randomActivation` property to the `ADD_NODE` object and a check to see if it's set to true (it is by default, but can be overwritten)

Closing for now
