### ISSUE TITLE
Moved: Allow bundling with Webpack

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#38]
This bug has been moved from Neataptic.
https://github.com/wagenaartje/neataptic/issues/57

The pull request:
https://github.com/wagenaartje/neataptic/pull/148

> Cannot resolve 'child_process' 
> ```
> ./~/neataptic/src/multithreading/workers/node/testworker.js
> Module not found: Error: Can't resolve 'child_process' in '[...]/node_modules/neataptic/src/multithreading/workers/node'
>  @ ./~/neataptic/src/multithreading/workers/node/testworker.js 7:9-33
>  @ ./~/neataptic/src/multithreading/workers/workers.js
>  @ ./~/neataptic/src/multithreading/multi.js
>  @ ./~/neataptic/src/neataptic.js
> ```

**Comment by christianechevarria** [comment]
Added the PR contribution in d6e13e25d83960773024dae64d9beb7dc142c3ee

Closing for now
