### ISSUE TITLE
Moved: NEAT breaks with provenance with if no template network is provided

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#43]
This bug has been moved from Neataptic.
https://github.com/wagenaartje/neataptic/issues/145

> While `createPool()` gracefully handles the no-template case, provenance doesn't. You could simply set the default network (`new Network(this.input, this.output)`) when none is provided and simplify `createPool()`

**Comment by christianechevarria** [comment]
Fixed in a013b149b084703a93c9e0d433fecd1e3487cd36

**Comment by dan-ryan** [comment]
@christianechevarria added one code comment. It's minor so you can ignore it.
