### ISSUE TITLE
Moved: Neat's input and output parameters are useless if a network is provided

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#44]
This suggestion has been moved from Neataptic.
https://github.com/wagenaartje/neataptic/issues/144

> So I checked the code, at least within the `neat` module, the first 2 arguments (inputs and outputs) are only use to create the random network if none is provided.
> 
> This means that if one is, those 2 are useless and hence the calling code looks awkward. I think it should make more sense to **make inputs and outputs also options** (heck, make it accept just a single options object) and hence they are optional and only used (and required) if no template network is provided.

> An extra comment, I notice that when a network is provided, it is used as a template as is. That means that either passing a random network or any other, means the first generation is all equal and does the same thing (AFAIU). Maybe it'd make sense to randomly mutate each template the first time?

**Comment by christianechevarria** [comment]
This has functionally been resolved by Neat's support for constructor overloading:

https://github.com/liquidcarrot/carrot/blob/e7eb40acfbf3eb1cf320c5ed37520dfeddd20fef/src/neat.js#L92-L111

Closing for now
