### ISSUE TITLE
LSTM and GRU creating large networks

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#59]
LSTM and GRU are creating large networks. 

E.g running "new Architect.LSTM(4, 5, 1)" seems to create a network of 100+ nodes.

**Comment by luiscarbonell** [comment]
@dan-ryan I'm having a hard time replicating this on my end - going to close for now.

![image](https://user-images.githubusercontent.com/21148993/58199515-a071cb80-7c9e-11e9-85c2-6febcb9c1da0.png)

**My Code**

```javascript
let { architect } = require("@liquid-carrot/carrot");

console.log([(new architect.LSTM(4, 5, 1)).nodes.length, (new architect.LSTM(4, 5, 1)).nodes.length, (new architect.LSTM(4, 5, 1)).nodes.length]) // [ 25, 25, 25 ]
console.log([(new architect.GRU(4, 5, 1)).nodes.length, (new architect.GRU(4, 5, 1)).nodes.length, (new architect.GRU(4, 5, 1)).nodes.length]) // [ 35, 35, 35 ]
```

**Comment by dan-ryan** [comment]
I was still getting it last night using Neat with the latest version. Try running my script I gave but make sure Neat creates `Architect.LSTM` instead of random.

**Comment by luiscarbonell** [comment]
I'll look into it.

**Comment by dan-ryan** [comment]
Actually, it seems that might not have come from LSTM. Looks like the https://github.com/liquidcarrot/carrot/issues/31 issue is going into overdrive.

**Comment by luiscarbonell** [comment]
Okay, I'll close for now.
