### ISSUE TITLE
Filter genomes

### ISSUE THREAD

**Issue by dan-ryan** [liquidcarrot/carrot#60]
I would like to see a way to filter out genomes from a Neat population so they are not evolved.

For example, some genomes are creating NaNs and evolving so more of my population will have the same issues. I would like to filter out or mark these genomes so they are no longer used.

**Comment by christianechevarria** [comment]
Added a removeGenome predicate function in 051b8f01863cbe1648abcfaa5e20cac08a861b0d

**Comment by christianechevarria** [comment]
Added custom genome selection function and adjustment functions in 5095c753a562546caa29b36f0cbfeb5011633b26

**Comment by dan-ryan** [comment]
@christianechevarria Looks like the latest change broke it. I left a comment.

**Comment by christianechevarria** [comment]
Seems resolved by dacf593812486d5c737b98a674b16fba9f7f6a36 

Closing for now

**Comment by christianechevarria** [comment]
Added some checks in ed426018433df661354e8effa5c58f04f39f6644
