### ISSUE TITLE
Less cohesive npm scripts

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#64]
**Is your feature request related to a problem? Please describe.**

It's frustrating to build the repo with current script; their very bulky and run a lot of processes at once (which often break). They are mostly event-triggered and are hard to avoid.

**Describe the solution you'd like**

Scripts that are independent of each other. Particularly as it relates to:
- Versioning
- Publishing
- Building Documenation
- Building bundled production code
- Running tests
- Running code coverage scripts

**Additional context**
![image](https://user-images.githubusercontent.com/21148993/57498998-024c3180-72ac-11e9-975e-b1067f441a18.png)

@christianechevarria Am I missing a script or something? I'm trying to just version the repo - or just build the documentation page (without anything else triggering). 

I know for documentation building, I can run `npm run build:docs`. Is there anything similar for `version`?

**Comment by christianechevarria** [comment]
Moved `version` hooks to `version:deep` as of 0f2d149ec62188b0d1c6b3c5e1bf92dfc1766780
