### ISSUE TITLE
Use brain.js for non evolution?

### ISSUE THREAD

**Issue by lagleki** [liquidcarrot/carrot#69]
Remaking your in "yet another js lib for more" might not be optimal. Why not use brain.js (which supports GPU among other things) for non evolution but retain Instinct algorithm as is?

**Comment by christianechevarria** [comment]
Hey @lagleki 👋  

Thank you for the first issue! 😄  🙏 

We think Brain.js is **fantastic** - 'specially [GPU.js](https://github.com/gpujs/gpu.js) by [Robert](https://github.com/robertleeplummerjr) and the streaming he's built in already (very cool) -, but there were some really great things that originally attracted us to Neataptic - and [Thomas](https://github.com/wagenaartje/) - as a foundation that hasn't (yet) been built into brain.js:

- The fine-grained control of building structures all the way from networks, groups, layers, down to nodes
- The ease of changing structures (networks, groups, nodes) AFTER we create them (one of the things we love the most about Carrot)
- The wonderful neuro-evolution methods (of course)

In short, most of the things we love about Carrot have to do with the _architecture_ which will start to pay off more as we:
- Add new & better evolutionary algorithms
- Add reinforcement learning
- Begin to blend different learning styles
- Double down on "irregular" network topologies to solve larger classes of problems 
- And add different behaviors to the nodes themselves (a lot of stuff we're dying to try out)

Right now we're in a cleaning and testing stage in the project to get it to the point where we can start  quickly expanding it in new directions. We really love brain.js but we think that it would be more difficult to accomplish some of the things we have planned on brain.js' architecture.

We'll likely end up helping with GPU.js in the near future - but it will be hard for us to take this project where we want and adopt Brain.js as our core. Definitely keeping our eyes peeled though 👀

Our goal is just to make an awesome library we can enjoy using and can be easy to add the latest bells and whistles to.
