### ISSUE TITLE
Add descriptive return type to Network.evolve() Docs

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#70]

**Comment by christianechevarria** [comment]
![image](https://user-images.githubusercontent.com/23618650/58767474-9a5ed300-8559-11e9-995a-88baa4a19799.png)

**Comment by christianechevarria** [comment]
Added more descriptive object return description in 4f356f5fae509bb58a919c8388af62e43a8af990

Closing for now
