### ISSUE TITLE
Network.evolve() & Neat.evolve() not mutating network 

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#71]
### Description

Running `network.evolve()` & `Neat.evolve()` both are producing silent failures or not evolving the the network.

### To Reproduce

Using `Node.js v10.15.3` and running the following code, produces the following error.

### Expected behavior

* none of the created networks to throw an error 
* the error value to change

### Additional context

There is a large possibility that a large part of this error is coming from the fact that because the output neurons are no longer mutable and the activation functions thereof default to `sigmoid`, regression output outside of the `(0, 1)` can create huge network training issue - _like experienced here_.

**Comment by christianechevarria** [comment]
@luiscarbonell do you have a code snippet that will cause this error? There have been some recent changes to Neat in an experimental branch and I'd like to see if this bug was resolved.
