### ISSUE TITLE
[Neat] Increase population size after Neat.fromJSON()

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#74]
### Describe the solution you'd like

Increase/Decrease `Neat.popsize` after `Neat.import()`

### Additional context

**Example Code**

```javascript
let pop = new Neat(3, 2);
pop.import(population);

let index = new_size - population.length - 1;
while(index < new_size) {
  pop.population.push(pop.getOffspring());
  index++;
}
```
![Screenshot 2019-05-22 at 12 34 30 PM](https://user-images.githubusercontent.com/21148993/58192106-02760500-7c8e-11e9-87a9-c61558365e5c.png)

![image](https://user-images.githubusercontent.com/21148993/58192090-fa1dca00-7c8d-11e9-9ba9-adf8734b2145.png)

**Comment by dan-ryan** [comment]
This is the code I used to get it working.
```
let index = PLAYER_AMOUNT - neat.population.length;
neat.popsize = PLAYER_AMOUNT;
if (index < 0) {
    //Reduce population
    neat.population.length = PLAYER_AMOUNT;
} else {
    while (index-- > 0) {
        neat.population.push(neat.getOffspring());
    }
}

```

**Comment by christianechevarria** [comment]
Added this as `Neat.resize` in 96d055e5bb67c20d2ba8bd825d7998f1eb2b9dc8

Here's the code
```
self.resize = function(update) {
    if(typeof update == 'number' || typeof update == 'string' &&	+update === +update) {
      let offset = update - self.population.length;

      if(offset > 0) {
        while(offset-- > 0) self.population.push(self.getOffspring())
      } else {
        while(offset++ < 0) self.population.pop() // if population sorted, removes least fit first
      }
    } else if (Array.isArray(update) && update.length) {
      for(let i = 0; i < update.length; i++) self.population.push(update[i])
    } else {
      throw new Error("Neat.resize needs a number or an array of new population members!")
    }

    self.population_size = self.population.length

    return self.population
}
```

Figured it would be nice to pass both a population to add to the existing one and a target population size and have the details handled by the method 

Adding basic tests now

**Comment by christianechevarria** [comment]
Will also update `Neat.fromJSON` to "mount" on top of `Neat.resize`

**Comment by christianechevarria** [comment]
Added tests in a5a6f8aef8fbf92e2053161e66c1fda3898135e6

**Comment by christianechevarria** [comment]
Looks like this was already addressed here:

https://github.com/liquidcarrot/carrot/blob/c991b950d36be4ff0948ac6e14897d40e1155a98/src/neat.js#L720

Closing for now
