### ISSUE TITLE
Fix architect.Construct to avoid throwing incorrect RangeErrors

### ISSUE THREAD

**Issue by AkashSamlal** [liquidcarrot/carrot#78]
**Describe the bug**
 * When creating a multilayer perceptron, 
     with the Input: 3 neurons, Hidden: 0 neurons, and Output: 1 neuron 

   *expect(new architect.Perceptron(3, 0, 1)).to.be.an.instanceOf(Network);*

![image](https://user-images.githubusercontent.com/43329669/58478364-e4902080-8123-11e9-99f6-e82804aaf742.png)

* It would fail to create one since the output error would be: 

**_RangeError: Inputs or outputs were set to zero, can't construct Network without input/output nodes!_**

**To Reproduce**
1. *Go* to **architecture** and *click* on the left triangle
2. *Scroll down* to **units** and *click* on the left triangle
3. *Scroll down* to **architecture** and *click* on the left triangle
4. *Click on* **architect.test.js** 
5. In the terminal, run *npm test*

**Expected behavior**
* It should fail on returning a multilayer perceptron due to 0 hidden layers, however, if you insert greater than 0, for instance, 1 neuron in 1 hidden layer, it should pass successfully 

![image](https://user-images.githubusercontent.com/43329669/58478318-c75b5200-8123-11e9-8fd3-c8cbfd7cd446.png)

**Possible Solution** 
The issue might be somewhere in the architect.Construct function, within this code: 

![image](https://user-images.githubusercontent.com/43329669/58479216-ce835f80-8125-11e9-8d41-a9830216012a.png)
 

**Desktop:**
 - OS: Windows 10 and Chrome OS
 - Version: VSCode 1.34.0

**Comment by dudesparsh** [comment]
Isn't what you are asking - MLP with 0 hidden layers practically wrong ?? How can it be MLP with no hidden layers ?

**Comment by luiscarbonell** [comment]
@AkashSamlal Maybe adding a more descriptive error message could be a fix...?

**Comment by AkashSamlal** [comment]
**Apologies everyone,**        

**Main Source of the Problem:** 
![image](https://user-images.githubusercontent.com/43329669/59240320-f9fc5480-8bd1-11e9-9af2-6513c63313dd.png)

Specifically, the issue is prevalent on the if and else check for determining if a particular node type is an output or input. Based on basic testing if statement, the check wasn't really checking the if the node type is an output or input, it just enters the first if check so in this case, the check only gave node type to output and didn't assign a node type to input, which would in then, return 0 input nodes and 4 output nodes. Even though in the unit test, we test for 3 input neurons, 0 hidden layers, 1 output neurons.  

**Solution:**

![image](https://user-images.githubusercontent.com/43329669/59240457-8ad33000-8bd2-11e9-8d19-c4a0305dbdba.png)

Overall, the main edit was checking the sum of the nodes[i].connections.in.length with the nodes[i].connections.out.length to determine if it's 0 or not. 

A commit will soon fix this issue!

**Comment by christianechevarria** [comment]
Circling back around to this, not sure that it's relevant anymore in light of recent changes to the codebase

Closing for now
